### ISSUE TITLE
Cant get recognized in notification settings

### ISSUE THREAD

**Issue by iamhenry** [Krojack/SABnzdb_discord#1]
after selecting a directory for the script, i have not been able to get the script to show up in the dropdown under notifications?

any ideas on how to get this to work? thx in advance

![image](https://github.com/Krojack/SABnzdb_discord/assets/923439/f27fcd84-1aeb-451e-9f40-57236774dcdb)

**Comment by Krojack** [comment]
Make sure it's in the correct folder. I had this at first.

https://sabnzbd.org/wiki/configuration/4.1/folders

Set the "Scripts Folder" path.  Mine is "/app/nzbnotify" but I run SABnzdb in Docker.

**Comment by iamhenry** [comment]
thx. i also run mine in docker hosted on Casa OS

this is the path i have that cant recognize the file: `sabnzbd/config/scripts`

i'm a bit confused even after looking at the link you sent. any suggestions? do I need to uncomment the `#` for the script to run?

**Comment by iamhenry** [comment]
i just added a new folder but it still wont recognize it
![image](https://github.com/Krojack/SABnzdb_discord/assets/923439/0b5df53e-03b2-4b0d-baca-4950d78f4ef9)

**Comment by Krojack** [comment]
put the script in /config/app

Make sure the script is executable as well (chmod +x discord-SAB.sh). To do this you might have to connect to the docker instance via console. I use Portainer to manage Docker and connect to a console this way.

**Comment by iamhenry** [comment]
gotcha. i think you're right with it not executing. i'm not familiar with the console so i will have to play with this another time. i dont want ruin my setup since i dont know what i'm doing 

appreciate the quick response

**Comment by iamhenry** [comment]
i got it working, thx! had to change a few dir via console to execute the file but it sent a test successfully

will it work for all enabled messages i have here?
![image](https://github.com/Krojack/SABnzdb_discord/assets/923439/20d3a8e4-9819-4397-820a-6c3e72f7189b)

**Comment by Krojack** [comment]
I haven't tested with all but it should.

**Comment by iamhenry** [comment]
cool, thx again

**Comment by Krojack** [comment]
I haven't tested with all but it should.
